export const sentencesArray = [
    // 1 Polar Bear
    { id: 1, order: 1, sentence: "In the Arctic's icy expanse, Dr. Emma Frost trudged through snow, her eyes scanning for polar bears."},
    { id: 1, order: 2, sentence: 'Melting ice crackled beneath her feet, a stark reminder of the warming world she studied tirelessly.'},
    { id: 1, order: 3, sentence: 'Through her binoculars, Emma spotted a mother bear and cubs, their ribs visible beneath matted fur.'},
    { id: 1, order: 4, sentence: 'Back at the research station, satellite images revealed vast blue where white ice once dominated the landscape.'},
    { id: 1, order: 5, sentence: "Emma's Inuit guide shared stories of changing hunting patterns, both for bears and for his people."},
    { id: 1, order: 6, sentence: "In a distant city, policymakers debated climate action while Emma's urgent reports piled on their desks."},
    { id: 1, order: 7, sentence: 'Children in classrooms across the globe learned about polar bears, becoming advocates for Arctic conservation.'},
    { id: 1, order: 8, sentence: "Emma's team tagged another bear, its data joining a growing network of climate change evidence."},
    { id: 1, order: 9, sentence: 'As temperatures rose, tourists flocked north, hoping to glimpse the iconic bears before it was too late.'},
    { id: 1, order: 10, sentence: 'In the face of melting ice and uncertain futures, Emma and her bears persevered, symbols of resilience.'},

    // 2 Polar Bear
    { id: 2, order: 1, sentence: 'The Arctic glacier stood silently, witnessing centuries of harsh weather and the ebb and flow of life.'},
    { id: 2, order: 2, sentence: "As global temperatures rose, the glacier felt itself slowly melting, becoming increasingly fragile with each passing year."},
    { id: 2, order: 3, sentence: 'The glacier watched a polar bear mother and her cubs struggling to find food on the shrinking ice floes.'},
    { id: 2, order: 4, sentence: 'Each summer, the glacier heard more ice breaking and saw more polar bears forced to swim towards distant land.'},
    { id: 2, order: 5, sentence: 'The glacier reminisced about the vast ice sheets of the past, where polar bears once roamed and hunted freely.'},
    { id: 2, order: 6, sentence: "Scientists arrived at the glacier's base, measuring its thickness and recording the annual ice loss with growing concern."},
    { id: 2, order: 7, sentence: 'The glacier observed greenhouse gases emitted by humans far away, understanding these invisible substances were accelerating its decline.'},
    { id: 2, order: 8, sentence: 'Local Inuit people shared stories of the glacier with their children, teaching them to cherish and protect this ancient icy world.'},
    { id: 2, order: 9, sentence: 'Though constantly shrinking, the glacier strived to maintain the surrounding ecological balance, providing habitat for Arctic creatures.'},
    { id: 2, order: 10, sentence: 'The glacier silently hoped humans would take action, allowing it to continue guarding this Arctic realm of life.'},

    // 3 Polar Bear
    { id: 3, order: 1, sentence: "Nanuk's massive paws crunched on the Arctic ice as he patrolled his territory. Suddenly, his sensitive nose detected something terribly wrong."},
    { id: 3, order: 2, sentence: 'The strange scent grew stronger with each step. Rounding a towering iceberg, Nanuk froze at the sight of black goo spreading across the water.'},
    { id: 3, order: 3, sentence: 'A distressed seabird flapped helplessly nearby, its wings heavy with thick oil. Nanuk watched with a mixture of curiosity and growing concern'},
    { id: 3, order: 4, sentence: "Where were the plump seals and silvery fish? Nanuk's stomach growled fiercely as he searched the contaminated waters, finding no trace of prey."},
    { id: 3, order: 5, sentence: "Strange figures appeared on the horizon, catching Nanuk's attention. Humans in bulky suits moved awkwardly, working to contain the expanding oil slick."},
    { id: 3, order: 6, sentence: "Nanuk's usually pristine white coat now bore dark, oily streaks. He licked his paw instinctively but recoiled at the foul, unfamiliar taste."},
    { id: 3, order: 7, sentence: 'Other polar bears began to gather, their confusion evident. Some rubbed frantically against ice chunks, trying desperately to clean their contaminated fur.'},
    { id: 3, order: 8, sentence: "Humans with large cameras approached cautiously. Nanuk stood his ground, watching curiously as they documented the disaster's impact on wildlife."},
    { id: 3, order: 9, sentence: 'As days passed, Nanuk learned to navigate around the worst-hit areas. He began guiding other bears to cleaner hunting grounds, adapting to change.'},
    { id: 3, order: 10, sentence: "Though the oil spill's effects lingered, Nanuk's resilience never wavered. In his enduring strength, there remained hope for the Arctic's future."},

    // 4 Dolphin
    { id: 4, order: 1, sentence: "Echo darted through the waves, clicking happily. Her pod's whistles echoed in the clear blue waters."},
    { id: 4, order: 2, sentence: 'A low rumble shook the sea. Echo froze, her sensitive ears hurting from the strange noise.'},
    { id: 4, order: 3, sentence: "Days passed. The rumbling grew louder. Echo struggled to hear her family's calls over the din."},
    { id: 4, order: 4, sentence: 'Where had all the fish gone? Echo searched, but her echolocation was useless against the constant noise.'},
    { id: 4, order: 5, sentence: "Metal giants appeared above. Their spinning blades churned the water, filling Echo's world with sound."},
    { id: 4, order: 6, sentence: "The pod's eldest led them away from home. Echo followed, longing for quiet seas."},
    { id: 4, order: 7, sentence: 'In new waters, Echo saw other creatures acting oddly. The noise was affecting everyone.'},
    { id: 4, order: 8, sentence: "The din followed them. Echo's mother showed her new ways to hunt without echolocation."},
    { id: 4, order: 9, sentence: 'Humans appeared one day, lowering strange objects into the water. Gradually, the noise lessened.'},
    { id: 4, order: 10, sentence: 'As quiet returned, Echo and her pod swam home. Hope for peaceful waters grew in their hearts.'},

    // 5 Dolphin
    { id: 5, order: 1, sentence: "The salty breeze whipped through Maya's hair as she scanned the horizon. A pod of dolphins leapt from the waves, catching her eye."},
    { id: 5, order: 2, sentence: "Frowning, Maya jotted notes in her weathered logbook. This pod was smaller than last year's, a trend she couldn't ignore."},
    { id: 5, order: 3, sentence: "A distant rumble drew her attention. Maya's grip tightened on the binoculars as a massive trawler came into view."},
    { id: 5, order: 4, sentence: "Helplessness washed over her as dolphins darted around the trawler's nets. Their panicked clicks echoed across the water."},
    { id: 5, order: 5, sentence: 'Back in her cramped lab, Maya pored over charts. Fish populations were plummeting, leaving dolphins with empty stomachs.'},
    { id: 5, order: 6, sentence: "'We're taking too much,' Maya explained to a group of weathered fishermen. Some nodded; others crossed their arms defensively."},
    { id: 5, order: 7, sentence: 'Nights blurred into days as Maya developed new fishing guidelines. She was determined to find a balance for all.'},
    { id: 5, order: 8, sentence: 'High-tech buoys bobbed in the waves, tracking dolphin movements. Maya needed data to protect their critical habitats.'},
    { id: 5, order: 9, sentence: 'Despite threatening letters and cold shoulders, Maya pushed on. She organized beach cleanups, spreading her message of conservation.'},
    { id: 5, order: 10, sentence: 'Months later, Maya smiled at a familiar dorsal fin. Slowly but surely, the dolphins were returning to healthier waters.'},

    // 6 Dolphin
    { id: 6, order: 1, sentence: "Clicks and whistles filled the water as Splash and his pod glided through their vast blue home. The young bottlenose dolphin reveled in the ocean's wonders."},
    { id: 6, order: 2, sentence: "Something caught Splash's eye - a strange, transparent object drifting nearby. Intrigued, he poked it with his beak. Was this a new kind of jellyfish?"},
    { id: 6, order: 3, sentence: 'These odd items became more common. Splash watched, puzzled, as his friends gobbled up colorful pieces, mistaking them for tasty treats.'},
    { id: 6, order: 4, sentence: "Hunting became harder as fish grew scarce. Splash couldn't understand why some of his podmates were moving slower, looking sickly."},
    { id: 6, order: 5, sentence: 'The pod gathered around an elder, his clicks grave. He spoke of "plastic," a human-made danger. Splash listened, his heart heavy with newfound understanding.'},
    { id: 6, order: 6, sentence: "Splash took action, warning fellow sea dwellers about the plastic threat. His echolocation became a tool for safety, helping detect and avoid the dangerous debris."},
    { id: 6, order: 7, sentence: 'Humans appeared one day, scooping plastic from the waves. Splash watched curiously, drawn to their cleanup efforts despite his caution.'},
    { id: 6, order: 8, sentence: "Near the coast, Splash heard children's voices learning about ocean protection. He leapt with joy, sensing a positive shift in human awareness."},
    { id: 6, order: 9, sentence: "Gradually, Splash's home became cleaner. Fish returned, and his pod's health improved. The ocean seemed to be healing."},
    { id: 6, order: 10, sentence: 'Hope swelled in Splash as he guided his pod through safer waters. Perhaps dolphins and humans could share a clean, thriving ocean after all.'},

    // 7 Penguin
    { id: 7, order: 1, sentence: 'Pip the penguin waddled across the icy Antarctic shore, unaware of the changes happening in his environment.'},
    { id: 7, order: 2, sentence: 'Marine biologists Sarah and Mike arrived to study the effects of climate change on penguin populations.'},
    { id: 7, order: 3, sentence: "They observed Pip's colony struggling to find food as warming waters altered fish migration patterns."},
    { id: 7, order: 4, sentence: "The scientists recorded data on shrinking ice sheets and rising sea temperatures around the penguins' habitat."},
    { id: 7, order: 5, sentence: 'Pip noticed his usual fishing spots were yielding fewer fish, forcing him to swim farther for meals.'},
    { id: 7, order: 6, sentence: 'Sarah and Mike shared their findings with colleagues, highlighting the urgent need for climate action.'},
    { id: 7, order: 7, sentence: "As years passed, Pip's colony adapted by altering their breeding patterns and foraging behaviors."},
    { id: 7, order: 8, sentence: 'The marine biologists continued their research, developing strategies to protect penguin habitats from further damage.'},
    { id: 7, order: 9, sentence: 'Pip and his fellow penguins became unwitting ambassadors for climate change awareness around the world.'},
    { id: 7, order: 10, sentence: "Through their resilience and the scientists' efforts, hope remained for the future of Antarctica's penguin populations."},

    // 8 Penguin
    { id: 8, order: 1, sentence: "Ice crunched under Pebble's feet as he waddled along the shore. The young emperor penguin's eyes sparkled with curiosity at his Antarctic home."},
    { id: 8, order: 2, sentence: 'Diving into the chilly waters, Pebble frowned. Where were all the krill? His stomach growled as he searched for his favorite snack.'},
    { id: 8, order: 3, sentence: "Brightly colored dots appeared on the horizon. Pebble cocked his head, watching as humans in neon jackets scurried about, dipping tubes into the sea."},
    { id: 8, order: 4, sentence: "Hushed voices drifted across the ice. 'Ocean acidification,' the humans muttered. Pebble didn't know the words, but their tone made his feathers ruffle."},
    { id: 8, order: 5, sentence: "Days passed, and food grew scarce. Pebble's heart sank as he saw once-plump adults struggling to feed their peeping chicks."},
    { id: 8, order: 6, sentence: 'More humans arrived, their tents dotting the icy landscape. They worked from sun-up to sundown, scribbling notes and peering at strange machines.'},
    { id: 8, order: 7, sentence: 'Curiosity overcame caution. Pebble inched closer to the busy humans, marveling at their dedication in the face of biting winds.'},
    { id: 8, order: 8, sentence: "Something new caught Pebble's eye. The humans were planting... in the ocean? Tiny green patches bobbed in the shallows."},
    { id: 8, order: 9, sentence: 'Weeks later, Pebble noticed a change. Krill danced around the green patches. His belly full once more, Pebble felt hope flutter in his chest.'},
    { id: 8, order: 10, sentence: "As seasons turned, Pebble grew to understand. These odd, two-legged creatures were friends, working tirelessly to save his icy kingdom."},

    // 9 Penguin
    { id: 9, order: 1, sentence: "Marine biologist Dr. Emily Stevens arrived at a remote Antarctic penguin research station, fully determined to study the severe impacts of overfishing on the local ecosystem's delicate balance."},
    { id: 9, order: 2, sentence: 'Every day, she observed the penguin colonies with great care, meticulously noting a disturbing decline in their population numbers and overall health conditions.'},
    { id: 9, order: 3, sentence: 'The primary food source for the penguins, krill, had significantly decreased due to rampant commercial fishing operations in the expansive Southern Ocean.'},
    { id: 9, order: 4, sentence: "Emily's detailed data revealed that overfishing had disrupted the entire marine ecosystem, leaving penguins struggling desperately to find enough food for survival."},
    { id: 9, order: 5, sentence: 'She compiled her comprehensive findings into a thoroughly detailed report, emphasizing the urgent need for stricter fishing regulations to protect the fragile marine life.'},
    { id: 9, order: 6, sentence: 'Various environmental organizations took immediate notice of her groundbreaking work, launching global campaigns to advocate strongly for sustainable fishing practices.'},
    { id: 9, order: 7, sentence: "Despite the harsh and isolating conditions of the Antarctic, Emily's dedication to her research never wavered, driven by her unwavering passion for marine conservation efforts."},
    { id: 9, order: 8, sentence: 'One cold and windy morning, she observed a starving penguin chick, which tragically reinforced the critical importance of her mission and ongoing research.'},
    { id: 9, order: 9, sentence: 'Months later, her persistent efforts finally bore fruit when new international policies were enacted, aiming to curb overfishing and protect crucial marine habitats.'},
    { id: 9, order: 10, sentence: 'Emily continued to monitor the gradual recovery of the penguin populations, feeling a cautious but steadily growing sense of hope for the future.'},
] 